### ISSUE TITLE
Import error in 0.86.0

### ISSUE THREAD

**Issue by yonikremer** [earendil-works/pi#9794]
### What happened?

When updating to 0.86.0 and updating all pi packages and reloading, got this error:
```
Error: Cannot find module
 'C:\Users\yonik\AppData\Roaming\npm\node_modules\@earendil-works\pi-coding-agent\dist\bundle\chunks\openai-responses-TFDINO6W.js' imported from
 C:\Users\yonik\AppData\Roaming\npm\node_modules\@earendil-works\pi-coding-agent\dist\bundle\chunks\chunk-JVUZSMYM.js
```

### Steps to reproduce

update to 0.86.0, install my user packages and update. I am using windows.
```
User packages:
  npm:@juicesharp/rpiv-ask-user-question
  npm:pi-background-tasks
  npm:@narumitw/pi-goal
  npm:@narumitw/pi-usage
  npm:pi-caveman
  npm:pi-smart-compact
  npm:pi-autoresearch
  npm:pi-extensible-workflows
  npm:@earendil-works/pi-server
  npm:@earendil-works/pi-tui
  npm:remote-pi
  npm:pi-worktrees
  npm:pi-queue-steer-factory
  npm:pi-fabric
  npm:pi-meta-oauth
  npm:@juicesharp/rpiv-todo
  npm:pi-lens
  npm:@dietrichgebert/ponytail
  npm:@injaneity/pi-computer-use
  npm:pi-btw
  npm:pi-web-search
```

### Version

0.86.0

**Comment by alex-piccione** [comment]
After updating Pi to 0.86.0 , on 3 difefrent containers, I have this error:

 Error: Cannot find module '/usr/lib/node_modules/@earendil-works/pi-coding-agent/dist/bundle/chunks/openai-completions-ERMU2SS7.js' imported from
 /usr/lib/node_modules/@earendil-works/pi-coding-agent/dist/bundle/chunks/chunk-OMWWHBTG.js

**Comment by ctbaum** [comment]
Additional macOS reproduction with enough timing information to identify the cause:

- A Pi 0.85.1 session started at 17:04:57.
- npm successfully replaced the global install with 0.86.1 at 17:05:23.
- The first OpenAI Codex request in the original session failed at 17:23:37 with `openai-codex-responses-R6VYZTVY.js` imported from `chunk-JVUZSMYM.js`.

The published 0.85.1 tarball contains both of those hashes. The 0.86.0 and 0.86.1 tarballs use `openai-codex-responses-QDSOTBBO.js` and no longer contain `chunk-JVUZSMYM.js`.

The live process therefore retained the 0.85.1 parent chunk in memory, then resolved its deferred provider import against the replaced 0.86.1 directory. A fresh 0.86.1 process works, and an integrity scan found 155 relative imports with zero missing targets.

This appears to be a general update lifecycle bug, not a corrupt tarball or a Windows-specific issue: updating the global package invalidates lazy imports in older live Pi sessions.

Minimal reproduction:

1. Install 0.85.1 and start an interactive Pi session without invoking a lazily loaded provider.
2. Upgrade the same global prefix to 0.86.x from another process.
3. Invoke that provider in the original session.
4. Observe `ERR_MODULE_NOT_FOUND` for the old content-hashed chunk.

Expected: an update should not invalidate a running session. At minimum, this condition should produce an explicit restart-required diagnostic rather than a misleading missing-module error.

**Comment by ctbaum** [comment]
AI disclosure: Codex collected the local timestamps, compared the published npm tarballs, and drafted the diagnostic comment above at the account owners request.
