### ISSUE TITLE
Cannot use SqliteSessionRepository with AgentSession (SessionManager hardcoded)

### ISSUE THREAD

**Issue by rzechen** [earendil-works/pi#9001]
### What happened?

```markdown
## Cannot use SqliteSessionRepository with AgentSession (SessionManager hardcoded)

### The problem

I'm running a multi-tenant backend where each user gets their own
`SESSION_DIR/<userId>/sessions.db`. I want to fully eliminate the
JSONL files that `AgentSession` writes, and use `SqliteSessionRepository`
from `@earendil-works/pi-session-backend-sqlite-node` instead.

`SessionRepo` / `SessionStorage` / `Session` are stable since
`pi-agent-core@0.84.0` (per the changelog), and `SqliteSessionRepository`
works fine on its own — I can create / list / appendMessage / getLeafId
without any issues.

But `createAgentSessionFromServices` refuses a `SessionRepo`. The
`sessionManager` field is typed as `SessionManager`, and injecting the
sqlite repo at runtime throws:

    sessionManager.buildSessionContext is not a function

### Why it matters

`SessionManager` is synchronous and file-based. `SessionRepo` is async
and backend-agnostic. I can't bridge them from the application side
because `SessionManager` exposes SDK-private methods
(`buildSessionContext`, `getTree`, `createBranchedSession`,
`branchWithSummary`, ...) that `SessionRepo` doesn't have.

I also checked `AgentHarness` — every core method (`prompt`, `compact`,
`navigateTree`, `steer`, `abort`, `resume`, ...) throws
`HarnessNotImplemented("X is not implemented yet")`, both in the
published `0.84.4` and on `main`.

### Repro

```bash
mkdir pi-sqlite-repro && cd pi-sqlite-repro
npm init -y >/dev/null
npm i @earendil-works/pi-coding-agent@0.84.4 \
       @earendil-works/pi-session-backend-sqlite-node@0.84.4 \
       tsx@4
```

```js
// repro.mjs
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { SqliteSessionRepository, createNodeSqliteFactory } from "@earendil-works/pi-session-backend-sqlite-node";
import { NodeExecutionEnv } from "@earendil-works/pi-agent-core/node";
import { createAgentSessionFromServices } from "@earendil-works/pi-coding-agent";

const tmp = mkdtempSync(join(tmpdir(), "pi-repro-"));
const repo = new SqliteSessionRepository({
  env: new NodeExecutionEnv({ cwd: tmp }),
  sqlite: createNodeSqliteFactory(),
  databasePath: join(tmp, "sessions.db"),
});

// 1) repo works standalone
const s = await repo.create({ cwd: tmp });
console.log("sqlite repo OK, id =", (await s.getMetadata()).id);

// 2) cannot inject into AgentSession
console.log("injecting into AgentSession...");
try {
  await createAgentSessionFromServices({
    services: { cwd: tmp, agentDir: tmp, modelRuntime: null,
      settingsManager: null, resourceLoader: null, diagnostics: [] },
    sessionManager: repo,
    sessionStartEvent: { type: "start" },
  });
  console.log("OK");
} catch (e) {
  console.log("FAILED:", e.message);
}
rmSync(tmp, { recursive: true, force: true });
```

```
node --import tsx repro.mjs
```

### Questions

1. Is migrating `AgentSession` to `AgentHarness` + `SessionRepo` on the
   roadmap? Rough version target?
2. Is `AgentHarness` actively being implemented? I see #7478 / #7503 /
   #7710 land the storage foundation, but the harness loop itself is
   still stubs.
3. Any supported way to plug a custom `SessionRepo` into `AgentSession`
   without forking?

I'd be willing to submit a PR if you point me at the right branch.
```


### Steps to reproduce


```markdown
1. Create a fresh project and install the relevant packages:

   ```bash
   mkdir pi-sqlite-repro && cd pi-sqlite-repro
   npm init -y >/dev/null
   npm i @earendil-works/pi-coding-agent@0.84.4 \
          @earendil-works/pi-session-backend-sqlite-node@0.84.4 \
          tsx@4
   ```

2. Save this as `repro.mjs`:

   ```js
   import { mkdtempSync, rmSync } from "node:fs";
   import { tmpdir } from "node:os";
   import { join } from "node:path";
   import { SqliteSessionRepository, createNodeSqliteFactory } from "@earendil-works/pi-session-backend-sqlite-node";
   import { NodeExecutionEnv } from "@earendil-works/pi-agent-core/node";
   import { createAgentSessionFromServices } from "@earendil-works/pi-coding-agent";

   const tmp = mkdtempSync(join(tmpdir(), "pi-repro-"));
   const repo = new SqliteSessionRepository({
     env: new NodeExecutionEnv({ cwd: tmp }),
     sqlite: createNodeSqliteFactory(),
     databasePath: join(tmp, "sessions.db"),
   });

   // Step 1: SqliteSessionRepository works on its own
   const s = await repo.create({ cwd: tmp });
   console.log("step 1 OK, sqlite session id =", (await s.getMetadata()).id);

   // Step 2: try to plug it into AgentSession
   console.log("step 2: injecting repo as sessionManager...");
   try {
     await createAgentSessionFromServices({
       services: {
         cwd: tmp, agentDir: tmp, modelRuntime: null,
         settingsManager: null, resourceLoader: null, diagnostics: [],
       },
       sessionManager: repo,
       sessionStartEvent: { type: "start" },
     });
     console.log("step 2 OK");
   } catch (e) {
     console.log("step 2 FAILED:", e.message);
   }
   rmSync(tmp, { recursive: true, force: true });
   ```

3. Run:

   ```bash
   node --import tsx repro.mjs
   ```

4. Expected: both steps succeed, or step 2 fails with a clear message
   saying `SessionRepo` is not yet supported by `AgentSession`.

5. Actual:

   ```
   step 1 OK, sqlite session id = 01a06154-a541-7ce4-bf61-4d4918a49990
   step 2: injecting repo as sessionManager...
   step 2 FAILED: sessionManager.buildSessionContext is not a function
   ```

   `AgentSession` calls `SessionManager`-specific synchronous methods
   (`buildSessionContext`, `getTree`, `createBranchedSession`,
   `branchWithSummary`, `appendCompaction`, ...) that are not part of
   the `SessionRepo` / `SessionStorage` contract, so the repo can't be
   substituted at runtime.
```

### Expected behavior

_No response_

### Version

_No response_
