### ISSUE TITLE
Esc during active streaming often fails to cancel the in-flight request until the provider finishes naturally

### ISSUE THREAD

**Issue by grelvshorem** [earendil-works/pi#8823]
# Title: Esc during active streaming often fails to cancel the in-flight request until the provider finishes naturally

## Summary

Pressing Esc while the model is actively streaming does not reliably cancel the HTTP request. The abort is registered (the turn eventually persists with `stopReason: "aborted"`), but only **after the provider finishes generating the entire response on its own** — tens of seconds later. During that window the UI keeps showing `working...` and the user believes interrupt is broken.

Reproduced with an OpenAI-compatible provider (Z.AI coding endpoint) delivering ~25 chunks/s. Abort behavior by phase:

| When Esc is pressed | Behavior |
|---|---|
| Before first chunk (request pending) | ✅ Cancels within ms (`AbortError` → error event → run settles) |
| During active streaming | ❌ Unreliable: request keeps streaming to completion; `aborted` message persisted only at natural end (~40s later in repros) |
| After message content finished, during run settle | ✅ Working indicator clears immediately |

## Instrumented evidence (patched build with timestamps)

- `agent.abort()` is called and the run's `AbortController` signal fires immediately on Esc.
- The signal is correctly passed to the OpenAI SDK request (`requestOptions.signal`).
- After abort during active streaming, SSE chunks continue to be consumed into the message content; the SDK's cancel never surfaces until the server closes the stream at natural completion.
- The full assistant text (i.e. the response the user tried to interrupt) ends up persisted, marked `aborted`.

## Likely mechanism

The delta → `updateContent` → synchronous markdown re-render chain (see the streaming re-render issue) keeps the event loop in continuous synchronous/microtask execution, so the socket-level cancellation triggered by the abort signal is not processed while deltas are flowing. Empirically, introducing macrotask boundaries in the update path (coalescing updates via `setTimeout`) makes aborts responsive — but the behavior remains racy: cancelation during heavy streaming should not depend on event-loop timing at all.

## Suggested fix

Make cancelation independent of the consumer: when the abort signal fires, synchronously destroy the response stream/reader (e.g. `reader.cancel()` / `response.body.destroy()` from an abort listener attached directly to the fetch), and have the SSE iterator reject immediately rather than after draining buffered chunks / waiting for the next read.

**Comment by CrazyCoder** [comment]
The same failure occurs on the Anthropic path, from the cause you describe: the abort is polled between reads, so a read that is already pending is never cancelled.

`packages/ai/src/api/anthropic-messages.ts:414-420`, at `v0.84.4` and unchanged on `main` at `4e69b0c28`:

```ts
while (true) {
    if (signal?.aborted) {
        throw new Error("Request was aborted");
    }

    const { value, done } = await reader.read();
```

That file contains no `reader.cancel()` and no `addEventListener("abort", ...)`. The check runs only when a read returns, so it cannot end a read that is in flight.

## How I reproduced it

I drove a real interactive TUI through a ConPTY: send a prompt, wait until the model is streaming, press Escape. Test harness and controls were identical across all runs; only the runtime and the model changed.

On the `anthropic` provider under bun 1.4.0 the turn never ends. The spinner keeps running, later Escape presses do nothing, and the session file stays empty, so the assistant output is lost instead of being stored with `stopReason: "aborted"`.

| runtime | model | Escape | result | bytes persisted |
|---|---|---|---|---|
| bun 1.4.0 | `claude-opus-5` | pressed | no abort, spinner runs | 0 |
| bun 1.4.0 | `claude-sonnet-5` | pressed | no abort, spinner runs | 0 |
| bun 1.4.0 | `claude-opus-5` | not pressed | turn completes | 22306 |
| node 26.8.1 | `claude-opus-5` | pressed | aborts correctly | 1676 |

8 of 8 runs wedged under bun, 3 of 3 aborted correctly under node. The paired control matters here, because pi writes nothing to the session file until a turn ends, so an unfinished run and a wedged run both show 0 bytes.

I reproduced this with only `@gotgenes/pi-anthropic-auth` loaded, and again with 26 extensions. It reproduces with and without a queued steering message, and at thinking levels `xhigh` and `off`.

## What the runtime split does and does not mean

Aborting a `fetch` rejects a pending `reader.read()` on bun 1.4.0 and on node 26, over both HTTP and HTTPS. I tested that directly, so raw `fetch` is not the difference. The signal is lost above the socket, and I did not identify where inside bun.

This is an inference rather than a measurement: the loop is unsafe on any runtime, and bun only makes it fire against a live provider. The regression test below supports that, because it fails on node.

I did not test the standalone binaries built by `build-binaries.sh`.

## Why #8593 does not cover this

PR #8593 changes 9 files, none under `packages/ai/`. It races `iterator.next()` against an idle timer that is cleared on every event, so the timer never fires while the model streams. It would convert this hang into a delayed failure after the timeout, and Escape would stay unresponsive.

## Patch

```diff
@@ -411,13 +411,40 @@ async function* iterateSseMessages(
 	const state: SseDecoderState = { event: null, data: [], raw: [] };
 	let buffer = "";
 
+	let onAbort: (() => void) | undefined;
+	let abortRejection: Promise<never> | undefined;
+	if (signal) {
+		abortRejection = new Promise<never>((_resolve, reject) => {
+			onAbort = () => {
+				void reader.cancel().catch(() => {});
+				reject(new Error("Request was aborted"));
+			};
+			signal.addEventListener("abort", onAbort, { once: true });
+		});
+		// The race leaves this rejection unobserved whenever a read wins, so mark it
+		// handled up front; otherwise aborting a completed stream would surface as an
+		// unhandled rejection.
+		abortRejection.catch(() => {});
+	}
+
 	try {
 		while (true) {
 			if (signal?.aborted) {
 				throw new Error("Request was aborted");
 			}
 
-			const { value, done } = await reader.read();
+			const { value, done } = abortRejection
+				? await Promise.race([reader.read(), abortRejection])
+				: await reader.read();
 			if (done) {
 				break;
 			}
@@ -457,6 +484,9 @@ async function* iterateSseMessages(
 			yield trailingEvent;
 		}
 	} finally {
+		if (signal && onAbort) {
+			signal.removeEventListener("abort", onAbort);
+		}
 		reader.releaseLock();
 	}
 }
```

The listener cancels the reader, and the race ends the read even when the stream does not reject on cancellation.

Two lines in that diff read as incidental and are not.

`void reader.cancel().catch(() => {})` observes a rejection rather than swallowing an exception. `cancel()` on a released reader **rejects**; it does not throw, so a `try`/`catch` around the call never sees it.

`signal.removeEventListener("abort", onAbort)` in the `finally` matters because the same `finally` releases the reader. A listener left behind outlives the reader it captured, and the next abort on that signal cancels a reader that is already detached.

Drop both and an abort raised after the stream has already finished takes the process down with an unhandled rejection:

```text
TypeError: Invalid state: The reader is not attached to a stream
 code: "ERR_INVALID_STATE"
```

I know because a build of mine carrying this fix without those two lines did exactly that to live sessions, on the second Escape, from `restoreQueuedMessagesToEditor` calling `abort()` a second time. The second test below covers it.

I verified the fix end to end by applying the same logic to a copy of the shipped bundle and rerunning the harness under bun: 4 of 4 runs aborted correctly, normal streaming still completed, and node still passed.

## Tests

Neither test needs credentials.

The first models a response that streams and then stops without closing, so the second read never settles. It times out against current `main` and passes with the patch, on node.

The second drains a complete turn and then aborts, which is the case above. It is mutation-proven: removing the `removeEventListener` call and the `.catch` fails it with that exact `ERR_INVALID_STATE`, and restoring them passes it.

<details>
<summary>packages/ai/test/anthropic-stream-abort-mid-stream.test.ts</summary>

```ts
import { describe, expect, it } from "vitest";
import { stream } from "../src/api/anthropic-messages.ts";
import type { Context, Model } from "../src/types.ts";

function testModel(): Model<"anthropic-messages"> {
	return {
		id: "claude-test",
		name: "Claude Test",
		api: "anthropic-messages",
		provider: "anthropic",
		baseUrl: "http://127.0.0.1:9",
		reasoning: false,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 200000,
		maxTokens: 32000,
	};
}

const SSE_PREFIX = [
	`event: message_start\ndata: ${JSON.stringify({
		type: "message_start",
		message: {
			id: "msg_1",
			type: "message",
			role: "assistant",
			model: "claude-test",
			content: [],
			stop_reason: null,
			usage: { input_tokens: 1, output_tokens: 1 },
		},
	})}\n\n`,
	`event: content_block_start\ndata: ${JSON.stringify({
		type: "content_block_start",
		index: 0,
		content_block: { type: "text", text: "" },
	})}\n\n`,
	`event: content_block_delta\ndata: ${JSON.stringify({
		type: "content_block_delta",
		index: 0,
		delta: { type: "text_delta", text: "hello" },
	})}\n\n`,
].join("");

const SSE_TAIL = [
	`event: content_block_stop\ndata: ${JSON.stringify({ type: "content_block_stop", index: 0 })}\n\n`,
	`event: message_delta\ndata: ${JSON.stringify({
		type: "message_delta",
		delta: { stop_reason: "end_turn", stop_sequence: null },
		usage: { output_tokens: 5 },
	})}\n\n`,
	`event: message_stop\ndata: ${JSON.stringify({ type: "message_stop" })}\n\n`,
].join("");

/**
 * A response that streams a little and then goes silent forever without closing
 * -- the shape of a provider still holding the connection open mid-response.
 *
 * The second `reader.read()` therefore never settles on its own. Polling
 * `signal.aborted` between reads cannot rescue that, because the check is only
 * reached if a read returns. The loop must react to the signal *while* a read is
 * pending, or the generator never returns and the whole turn hangs.
 */
function stallingFetch(): typeof fetch {
	return (async () => {
		const body = new ReadableStream<Uint8Array>({
			start(controller) {
				controller.enqueue(new TextEncoder().encode(SSE_PREFIX));
			},
			pull() {
				// Never resolves: no more data, no close, no error.
				return new Promise<void>(() => {});
			},
		});
		return new Response(body, {
			status: 200,
			headers: { "content-type": "text/event-stream" },
		});
	}) as unknown as typeof fetch;
}

/** A response that streams an entire turn and closes, the way every normal one does. */
function completingFetch(): typeof fetch {
	return (async () => {
		const body = new ReadableStream<Uint8Array>({
			start(controller) {
				controller.enqueue(new TextEncoder().encode(SSE_PREFIX + SSE_TAIL));
				controller.close();
			},
		});
		return new Response(body, {
			status: 200,
			headers: { "content-type": "text/event-stream" },
		});
	}) as unknown as typeof fetch;
}

describe("Anthropic stream abort mid-stream", () => {
	it("ends the turn when the signal fires while a read is pending", async () => {
		const context: Context = {
			messages: [{ role: "user", content: "hi", timestamp: Date.now() }],
		};
		const controller = new AbortController();

		const response = stream(testModel(), context, {
			apiKey: "test-key",
			cacheRetention: "none",
			signal: controller.signal,
			fetch: stallingFetch(),
		});

		const drained = (async () => {
			for await (const event of response) {
				// Abort as soon as the model is visibly streaming, then stop reading.
				if (event.type === "text_delta") {
					controller.abort();
					return "streamed-then-aborted";
				}
			}
			return "ended-without-delta";
		})();

		// Before the fix this never settles, so the assertion below is what a hang
		// looks like as a test failure rather than a wedged runner.
		const outcome = await Promise.race([
			drained,
			new Promise<string>((resolve) => setTimeout(() => resolve("HUNG"), 5000)),
		]);
		expect(outcome).toBe("streamed-then-aborted");

		const message = await Promise.race([
			response.result(),
			new Promise<never>((_resolve, reject) =>
				setTimeout(() => reject(new Error("result() never settled after abort")), 5000),
			),
		]);
		expect(message.stopReason).toBe("aborted");
	}, 20000);

	// Cancelling the reader is only half of it. A stream that ends normally
	// releases its reader in the `finally`, so a listener left on the caller's
	// signal outlives the reader it captured. A later abort -- the next Escape,
	// or a turn the user interrupts after this one -- then cancels a released
	// reader. That *rejects* rather than throwing, so it survives any try/catch
	// around the call, and unobserved it takes the process down.
	//
	// This is not hypothetical. A minified build carrying this fix without both
	// guards crashed real sessions on the second Escape with "TypeError: Invalid
	// state: The reader is not attached to a stream" (ERR_INVALID_STATE).
	//
	// Each guard alone is unobservable from here, which is exactly why they are
	// easy to drop: removing only the listener leaves the rejection handled, and
	// keeping only the listener cancels a reader that is still live. Counting
	// listeners on the signal does not separate them either, because the SDK
	// attaches one of its own per request and never removes it.
	it("leaves nothing behind that a later abort can trip over", async () => {
		const context: Context = {
			messages: [{ role: "user", content: "hi", timestamp: Date.now() }],
		};
		const controller = new AbortController();

		const response = stream(testModel(), context, {
			apiKey: "test-key",
			cacheRetention: "none",
			signal: controller.signal,
			fetch: completingFetch(),
		});
		for await (const _event of response) {
			// Drain the turn to completion; nothing is aborted here.
		}
		expect((await response.result()).stopReason).toBe("stop");

		const rejections: unknown[] = [];
		const capture = (reason: unknown) => rejections.push(reason);
		process.on("unhandledRejection", capture);
		try {
			// The user presses Escape after the turn has already ended.
			controller.abort();
			// unhandledRejection is emitted after the microtask queue drains.
			await new Promise((resolve) => setTimeout(resolve, 100));
		} finally {
			process.off("unhandledRejection", capture);
		}
		expect(rejections.map(String)).toEqual([]);
	}, 20000);
});
```

</details>

`biome check` passes on both files. `vitest --run` in `packages/ai` reports 373 passed, one more than the same tree without this file; the 89 failing files there are pre-existing and identical with or without it, because they need generated model data. The 41 `tsgo` errors in my clone are `TS2307` for that same missing data.

I have since applied the same change to `mistral-conversations.ts`, `openai-codex-responses.ts` and `pi-messages.ts`. Those three are untested against a live provider.

Tell me if you want this as a PR.

**Comment by holny** [comment]
I spent some time instrumenting this against a local SSE server and could not reproduce the stream-to-natural-completion behavior on current main — flagging in case it is environment-specific.

Setup: continuous SSE stream (~40 chunks/s), consumer doing 20-40ms of sync work per chunk to mimic the render loop, tested with fast and slow (buffer-building) consumers, on current main (9767ba275, openai 6.40.0) and re-tested with openai 6.26.0 (what pi-ai 0.84.1 pinned). On both consumption paths the pending read settles within ~10-20ms of `controller.abort()`:

- raw body path (`iterateSseMessages` in `packages/ai/src/api/anthropic-messages.ts`)
- SDK stream path (`openai-completions.ts` / `openai-responses-shared.ts`)

`AbortSignal` listeners run synchronously and undici tears the socket down at abort time, so cancellation should not depend on the event loop getting a free macrotask — which makes me a bit doubt the starvation mechanism.

Two real gaps I did see on main, though minor next to the reported symptom: the OpenAI SDK path ends the stream silently on abort (only caught by the post-loop `signal.aborted` check at `openai-completions.ts:678`), and an `AbortError` escapes as an unhandled rejection from SDK internals.

Could you say whether this still reproduces on current main (0.85.x), and which node version and provider path you were on (openai-compatible completions? custom `fetch` override?)? If it is tied to an older node/undici or the endpoint's proxy, that would explain the difference.

This comment is AI-generated by `/wr`.

**Comment by Tre-vor-W** [comment]
The inferencing is cancelled but the pi harness still shows working - because the inferencing is cancelled the task never completes, the only way to disrupt the pi harness in this case is to quit

**Comment by davidbrai** [comment]
I tried reproducing using openai-completions and specifically against the z.ai provider with no success. closing the issue.
if you manage to reproduce let me know

**Comment by CrazyCoder** [comment]
> I tried reproducing using openai-completions and specifically against the z.ai provider with no success. closing the issue.
> if you manage to reproduce let me know

Did you try reproducing with bun? See my branch where the issue is gone after these patches and is always reproducible without.

**Comment by Tre-vor-W** [comment]
> > I tried reproducing using openai-completions and specifically against the z.ai provider with no success. closing the issue.
> > if you manage to reproduce let me know
> 
> Did you try reproducing with bun? See my branch where the issue is gone after these patches and is always reproducible without.

Agree on the bun angle, I only noticed this after upgrading to v85 which is coincidentally when I upgraded to bun 1.40 now 1.42

**Comment by davidbrai** [comment]
@CrazyCoder how were you running with bun? the bundled pi release? that's with 1.3.14

**Comment by CrazyCoder** [comment]
I run Pi's npm-installed JavaScript CLI under Bun, not the standalone executable. My launcher does this for faster startup, but I also reproduced the freeze without it, by invoking `bun /path/to/pi/dist/cli.js` directly.

The tests used Pi 0.84.4 on Windows with Bun 1.4.0: Escape during an Anthropic response froze all 8 runs. The same build under Node 26.8.1 aborted correctly in all 3 controls.

I tried Bun 1.3.14, but the npm bundle failed at startup with `TypeError: webidl.util.markAsUncloneable is not a function` from undici. That prevented testing cancellation on that version. I did not test the standalone binary.

**Comment by davidbrai** [comment]
pi currently only supports running with node, this seems to happen only with node runtime so I'm going to close this issue for now
