### ISSUE TITLE
[Deprecated] fix(coding-agent): sandbox example breaks root npm run check due to missing dependency

### ISSUE THREAD

**Issue by Phoen1xCode** [earendil-works/pi#4111]
**Package:** `packages/coding-agent`

`npm run check` fails with type errors in `packages/coding-agent/examples/extensions/sandbox/index.ts`:

```
packages/coding-agent/examples/extensions/sandbox/index.ts(47,59): error TS2307: Cannot find module '@anthropic-ai/sandbox-runtime' or its corresponding type declarations.
packages/coding-agent/examples/extensions/sandbox/index.ts(57,2): error TS2353: Object literal may only specify known properties, and 'network' does not exist in type 'SandboxConfig'.
...
```

**Root cause**

The sandbox extension has its own `package.json` with `@anthropic-ai/sandbox-runtime` as a dependency, and its `node_modules/` is gitignored. The root `npm install` does not install the sandbox's dependencies, so the module is never available to the TypeScript compiler.

The root `tsconfig.json` includes `packages/coding-agent/examples/**/*`, which causes the global type check to compile `sandbox/index.ts` — where it cannot resolve `@anthropic-ai/sandbox-runtime`.

Introduced in #673 (commit `4751ebdd`).

**Possible fixes**

1. Add `packages/coding-agent/examples/extensions/sandbox/` to the `exclude` list in the root `tsconfig.json`. The sandbox has its own isolated build environment and should not be part of the monorepo-wide type check.
2. Add `@anthropic-ai/sandbox-runtime` as a root-level devDependency so the module is available during `npm run check`.

**Comment by Phoen1xCode** [comment]
Sorry, my agent submit this issue automatically. Please ignore this issue.
